version: '3.7'
services:
  tz_db:
    image: postgres:12
    restart: "always"
    hostname: tz_db
    networks:
      - etl
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5433:5433
    env_file: ./book_site/book_site/.env

  django:
    container_name: tz_nordsoft
    build: .
    command: bash -c "python /usr/src/TZ_NordSoft/book_site/manage.py migrate --noinput &&
      python /usr/src/TZ_NordSoft/book_site/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/TZ_NordSoft
    ports:
      - 8000:8000
    env_file:
      - ./book_site/book_site/.env
    depends_on:
      - tz_db

networks:

  etl:

    driver: bridge


volumes:
  postgres_data:



