# Generated by Django 3.1.6 on 2021-03-03 20:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='верифицирован'),
        ),
        migrations.AddField(
            model_name='account',
            name='verification_uuid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Уникальный UUID проверки'),
        ),
    ]
