# Generated by Django 3.1.6 on 2021-03-03 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210303_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='account',
            name='verification_uuid',
        ),
    ]
