# Generated by Django 3.1.6 on 2021-03-14 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210209_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bought_books',
            field=models.IntegerField(default=0),
        ),
    ]
