# Generated by Django 3.1.6 on 2021-03-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_book_bought_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='number',
        ),
        migrations.AlterField(
            model_name='book',
            name='bought_books',
            field=models.IntegerField(default=0, verbose_name='Купленно книг'),
        ),
    ]
